### ISSUE TITLE
Not working on Ionic 3 (problem with sqliteplugin)

### ISSUE THREAD

**Issue by rklerck** [oscarfonts/mapbox-gl-cordova-mbtiles#1]
Great work on the plugin! I have stil one problem... I can't get it to work with the sqliteplugin. I keep getting the error that de plugin is not found. I installed it through npm because it didn't work with cordova plugin add. 

Do I have to do something else to get it to work?

**Comment by rklerck** [comment]
Fixed it by adding it directly in my index.html

`<script src="SQLitePlugin.js"></script>`

**Comment by JeongJun-Lee** [comment]
Hello, I am creating  a App with this plugin by Ionic5, but even I installed all required additional 3 cordova plugins("cordova-plugin-device","cordova-plugin-file","cordova-sqlite-ext"), when I executed this at browser, there is a error like below: 

Error: cordova-sqlite-ext plugin not available. Please install the pluginand make sure this code is run after onDeviceReady event

Do you have any hint to solve this?

**Comment by lasterra** [comment]
That plugin doesn't run on the browser. If you want to execute mapbox offline I recommend you to use custom:// tile load method modification on mapbox gl source code

**Comment by JeongJun-Lee** [comment]
@lasterra To load a local mbtiles file directly is not ready on mapbox gl js yet. It still seems to be on the feature request like https://github.com/mapbox/mapbox-gl-js/issues/4917 from mapbox gl js.
