### ISSUE TITLE
when using "osm-bright", labels are not displayed properly

### ISSUE THREAD

**Issue by jpilet** [oscarfonts/mapbox-gl-cordova-mbtiles#16]
I  tried to changed the style to osm-bright. It does not work properly: some map labels are not displayed.

My example is there
https://github.com/JpmGuides/mapbox-gl-cordova-mbtiles/tree/jp-osm-bright

unfortunately, map labels are not displayed properly.

I have trouble figuring out what is wrong here. Could you help?
Thanks

**Comment by oscarfonts** [comment]
At some point in time, the glyphs from free.tilehosting.com are no longer available, at least without a key.

Check the `glyphs` property in the style definition and update the URL. Try for instance with `http://fonts.openmaptiles.org/{fontstack}/{range}.pbf` which comes from this repo:
https://github.com/openmaptiles/fonts

Probably you will also have to change the "text-font" properties to any of the supported font names (I think "Noto Sans" is called "Klokantech Noto Sans": http://fonts.openmaptiles.org/fontstacks.json

Any of these has to do with this project, but with the external services from openmaptiles we are relying on.

Hope this helps.
