### ISSUE TITLE
iOS example app doesn't show map data

### ISSUE THREAD

**Issue by mb72** [oscarfonts/mapbox-gl-cordova-mbtiles#47]
I can get the iOS example app to open in the Xcode simulator, but it only shows the map controls, no map data. Any thoughts? @michogar @HarelM
Thanks

**Comment by HarelM** [comment]
I've seen issue with the simulator. I added `cordova-plugin-ionic-webview` to resolve issues in iOS, not sure this is what you experience though... iOS and their webview are not so good unfortunately...

**Comment by mb72** [comment]
@HarelM Thanks for the tip.
Nothing changed, but I did notice that `cordova-sqlite-ext` is still not installing despite using the fix suggested in #44, so I'm guessing that's the real source of the problem.
